extend type Amenity {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Amenity", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Amenity`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "Amenity.hotel", purpose: IMPLICIT_REF_FIELD)
}
extend type Booking {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Booking", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`guest`. It must match the value of `Guest`.`id`. See `@ref` for how to customize it.
  """
  guestId: UUID! @fdc_generated(from: "Booking.guest", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "Booking.hotel", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`room`. It must match the value of `Room`.`id`. See `@ref` for how to customize it.
  """
  roomId: UUID @fdc_generated(from: "Booking.room", purpose: IMPLICIT_REF_FIELD)
}
extend type Department {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Department", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Department`.`head`. It must match the value of `Staff`.`id`. See `@ref` for how to customize it.
  """
  headId: UUID @fdc_generated(from: "Department.head", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Department`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "Department.hotel", purpose: IMPLICIT_REF_FIELD)
}
extend type FinancialDocument {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "FinancialDocument", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `FinancialDocument`.`booking`. It must match the value of `Booking`.`id`. See `@ref` for how to customize it.
  """
  bookingId: UUID @fdc_generated(from: "FinancialDocument.booking", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `FinancialDocument`.`guest`. It must match the value of `Guest`.`id`. See `@ref` for how to customize it.
  """
  guestId: UUID @fdc_generated(from: "FinancialDocument.guest", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `FinancialDocument`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "FinancialDocument.hotel", purpose: IMPLICIT_REF_FIELD)
}
extend type Guest {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Guest", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Guest`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "Guest.hotel", purpose: IMPLICIT_REF_FIELD)
}
extend type Hotel {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Hotel", purpose: IMPLICIT_KEY_FIELD)
}
extend type HousekeepingTask {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "HousekeepingTask", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `HousekeepingTask`.`assignedTo`. It must match the value of `Staff`.`id`. See `@ref` for how to customize it.
  """
  assignedToId: UUID @fdc_generated(from: "HousekeepingTask.assignedTo", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `HousekeepingTask`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "HousekeepingTask.hotel", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `HousekeepingTask`.`room`. It must match the value of `Room`.`id`. See `@ref` for how to customize it.
  """
  roomId: UUID! @fdc_generated(from: "HousekeepingTask.room", purpose: IMPLICIT_REF_FIELD)
}
extend type InventoryItem {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "InventoryItem", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `InventoryItem`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "InventoryItem.hotel", purpose: IMPLICIT_REF_FIELD)
}
extend type Log {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Log", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Log`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "Log.hotel", purpose: IMPLICIT_REF_FIELD)
}
extend type MaintenanceRequest {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "MaintenanceRequest", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `MaintenanceRequest`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "MaintenanceRequest.hotel", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `MaintenanceRequest`.`room`. It must match the value of `Room`.`id`. See `@ref` for how to customize it.
  """
  roomId: UUID! @fdc_generated(from: "MaintenanceRequest.room", purpose: IMPLICIT_REF_FIELD)
}
extend type Room {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Room", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Room`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "Room.hotel", purpose: IMPLICIT_REF_FIELD)
}
extend type Shift {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Shift", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Shift`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "Shift.hotel", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Shift`.`staff`. It must match the value of `Staff`.`id`. See `@ref` for how to customize it.
  """
  staffId: UUID! @fdc_generated(from: "Shift.staff", purpose: IMPLICIT_REF_FIELD)
}
extend type Staff {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Staff", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Staff`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "Staff.hotel", purpose: IMPLICIT_REF_FIELD)
}
extend type StoredDocument {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "StoredDocument", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `StoredDocument`.`guest`. It must match the value of `Guest`.`id`. See `@ref` for how to customize it.
  """
  guestId: UUID @fdc_generated(from: "StoredDocument.guest", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `StoredDocument`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "StoredDocument.hotel", purpose: IMPLICIT_REF_FIELD)
}
extend type TimeLog {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "TimeLog", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `TimeLog`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "TimeLog.hotel", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `TimeLog`.`staff`. It must match the value of `Staff`.`id`. See `@ref` for how to customize it.
  """
  staffId: UUID! @fdc_generated(from: "TimeLog.staff", purpose: IMPLICIT_REF_FIELD)
}
extend type UserHotel {
  """
  ✨ Implicit foreign key field based on `UserHotel`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "UserHotel.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `UserHotel`.`hotel`. It must match the value of `Hotel`.`id`. See `@ref` for how to customize it.
  """
  hotelId: UUID! @fdc_generated(from: "UserHotel.hotel", purpose: IMPLICIT_REF_FIELD)
}
