extend type Query {
  """
  ✨ Look up a single `AiUsage` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  aiUsage(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AiUsage_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiUsage_FirstRow
  ): AiUsage @fdc_generated(from: "AiUsage", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Amenity` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  amenity(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Amenity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Amenity_FirstRow
  ): Amenity @fdc_generated(from: "Amenity", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Booking` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  booking(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Booking_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Booking_FirstRow
  ): Booking @fdc_generated(from: "Booking", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Department` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  department(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Department_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Department_FirstRow
  ): Department @fdc_generated(from: "Department", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `FinancialDocument` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  financialDocument(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FinancialDocument_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FinancialDocument_FirstRow
  ): FinancialDocument @fdc_generated(from: "FinancialDocument", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Guest` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  guest(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Guest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Guest_FirstRow
  ): Guest @fdc_generated(from: "Guest", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Hotel` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  hotel(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Hotel_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Hotel_FirstRow
  ): Hotel @fdc_generated(from: "Hotel", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `HousekeepingTask` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  housekeepingTask(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: HousekeepingTask_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: HousekeepingTask_FirstRow
  ): HousekeepingTask @fdc_generated(from: "HousekeepingTask", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `InventoryItem` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  inventoryItem(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: InventoryItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: InventoryItem_FirstRow
  ): InventoryItem @fdc_generated(from: "InventoryItem", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Log` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  log(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Log_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Log_FirstRow
  ): Log @fdc_generated(from: "Log", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MaintenanceRequest` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  maintenanceRequest(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MaintenanceRequest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MaintenanceRequest_FirstRow
  ): MaintenanceRequest @fdc_generated(from: "MaintenanceRequest", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Room` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  room(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Room_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Room_FirstRow
  ): Room @fdc_generated(from: "Room", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Shift` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  shift(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Shift_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Shift_FirstRow
  ): Shift @fdc_generated(from: "Shift", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Staff` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  staff(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Staff_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Staff_FirstRow
  ): Staff @fdc_generated(from: "Staff", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `StoredDocument` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  storedDocument(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StoredDocument_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StoredDocument_FirstRow
  ): StoredDocument @fdc_generated(from: "StoredDocument", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TimeLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  timeLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TimeLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TimeLog_FirstRow
  ): TimeLog @fdc_generated(from: "TimeLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserHotel` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userHotel(
    """
    The key used to identify the object.
    """
    key: UserHotel_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserHotel_FirstRow
  ): UserHotel @fdc_generated(from: "UserHotel", purpose: QUERY_SINGLE)
  """
  ✨ List `AiUsage` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  aiUsages(
    """
    Filter condition to narrow down the query results.
    """
    where: AiUsage_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AiUsage_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AiUsage_Having
  ): [AiUsage!]! @fdc_generated(from: "AiUsage", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Amenity` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  amenities(
    """
    Filter condition to narrow down the query results.
    """
    where: Amenity_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Amenity_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Amenity_Having
  ): [Amenity!]! @fdc_generated(from: "Amenity", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Booking` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  bookings(
    """
    Filter condition to narrow down the query results.
    """
    where: Booking_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Booking_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Booking_Having
  ): [Booking!]! @fdc_generated(from: "Booking", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Department` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  departments(
    """
    Filter condition to narrow down the query results.
    """
    where: Department_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Department_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Department_Having
  ): [Department!]! @fdc_generated(from: "Department", purpose: QUERY_MULTIPLE)
  """
  ✨ List `FinancialDocument` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  financialDocuments(
    """
    Filter condition to narrow down the query results.
    """
    where: FinancialDocument_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FinancialDocument_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FinancialDocument_Having
  ): [FinancialDocument!]! @fdc_generated(from: "FinancialDocument", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Guest` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  guests(
    """
    Filter condition to narrow down the query results.
    """
    where: Guest_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Guest_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Guest_Having
  ): [Guest!]! @fdc_generated(from: "Guest", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Hotel` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  hotels(
    """
    Filter condition to narrow down the query results.
    """
    where: Hotel_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Hotel_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Hotel_Having
  ): [Hotel!]! @fdc_generated(from: "Hotel", purpose: QUERY_MULTIPLE)
  """
  ✨ List `HousekeepingTask` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  housekeepingTasks(
    """
    Filter condition to narrow down the query results.
    """
    where: HousekeepingTask_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [HousekeepingTask_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: HousekeepingTask_Having
  ): [HousekeepingTask!]! @fdc_generated(from: "HousekeepingTask", purpose: QUERY_MULTIPLE)
  """
  ✨ List `InventoryItem` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  inventoryItems(
    """
    Filter condition to narrow down the query results.
    """
    where: InventoryItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [InventoryItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: InventoryItem_Having
  ): [InventoryItem!]! @fdc_generated(from: "InventoryItem", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Log` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  logs(
    """
    Filter condition to narrow down the query results.
    """
    where: Log_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Log_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Log_Having
  ): [Log!]! @fdc_generated(from: "Log", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MaintenanceRequest` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  maintenanceRequests(
    """
    Filter condition to narrow down the query results.
    """
    where: MaintenanceRequest_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MaintenanceRequest_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MaintenanceRequest_Having
  ): [MaintenanceRequest!]! @fdc_generated(from: "MaintenanceRequest", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Room` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  rooms(
    """
    Filter condition to narrow down the query results.
    """
    where: Room_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Room_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Room_Having
  ): [Room!]! @fdc_generated(from: "Room", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Shift` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  shifts(
    """
    Filter condition to narrow down the query results.
    """
    where: Shift_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Shift_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Shift_Having
  ): [Shift!]! @fdc_generated(from: "Shift", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Staff` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  staffs(
    """
    Filter condition to narrow down the query results.
    """
    where: Staff_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Staff_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Staff_Having
  ): [Staff!]! @fdc_generated(from: "Staff", purpose: QUERY_MULTIPLE)
  """
  ✨ List `StoredDocument` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  storedDocuments(
    """
    Filter condition to narrow down the query results.
    """
    where: StoredDocument_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StoredDocument_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StoredDocument_Having
  ): [StoredDocument!]! @fdc_generated(from: "StoredDocument", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TimeLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  timeLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: TimeLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TimeLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TimeLog_Having
  ): [TimeLog!]! @fdc_generated(from: "TimeLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserHotel` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userHotels(
    """
    Filter condition to narrow down the query results.
    """
    where: UserHotel_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserHotel_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserHotel_Having
  ): [UserHotel!]! @fdc_generated(from: "UserHotel", purpose: QUERY_MULTIPLE)
}
